name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Compile Java files (without running tests or dependencies)
      run: |
        javac -cp . LoginApp.java

    - name: Skip tests and dependencies
      run: echo "Skipping tests and dependencies as requested."
